dist: bionic

language: python

python: 3.7

services:
  - docker

jobs:
  include:
    - stage: Run tests
      name: Docker-compose with PostGIS database
      install:
        - cd ${TRAVIS_BUILD_DIR}/docker
        - docker-compose up -d --force-recreate
        - sleep 10
        - docker exec -it qgis sh -c "qgis_setup.sh raepa"
        - docker cp postgis_connections.ini qgis:/tmp
        - docker exec qgis bash -c "cat /tmp/postgis_connections.ini >> /root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini"
      script:
        - docker exec -it qgis sh -c "cd /tests_directory/raepa && qgis_testrunner.sh qgis_plugin_tools.infrastructure.test_runner.test_package"

    - stage: Deploy
      if: tag IS present
      name: Create release

      install:
        - pip3 install qgis-plugin-ci

      before_deploy:
        - export RELEASE_TITLE="Release of $TRAVIS_TAG"

      script:
        - qgis-plugin-ci -v

      deploy:

        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          api_key: ${GH_TOKEN}
          on:
            tags: true

        - provider: script
          script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --create-plugin-repo
          on:
            tags: true
