site_name: RAEPA
site_author: 3Liz
site_description: Extension QGIS pour les réseaux d'eaux
site_url: https://docs.3liz.org/qgis-raepa-plugin/
repo_url: https://github.com/3liz/qgis-raepa-plugin
copyright: '<span class="copyleft">&copy;</span> 3Liz'

docs_dir: docs
site_dir: build

nav:
    - Accueil: index.md
    - Guide utilisateur:
        - 'Installation': 'user-guide/installation.md'
        - 'Panneau RAEPA' : 'user-guide/panel.md'
        - 'Configuration' : 'user-guide/config.md'
        - 'Import-Export' : 'user-guide/import-export.md'
        - 'Outils' : 'user-guide/outils.md'
        - 'Actions' : 'user-guide/actions.md'
    - Processing: 'processing/README.md'
    - Changelog: changelog.md
    - Contribution: contributing.md
    - Base de données : database/index.html

markdown_extensions:
  - toc:
      permalink: "#"
  - meta:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
  - pymdownx.magiclink:
  - pymdownx.tasklist:
  - pymdownx.snippets:
  - pymdownx.keys:
  - attr_list:
  - admonition:
  - pymdownx.details:

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'fr'
  logo: media/icon.png
  favicon: media/icon.png
  palette:
    accent: deep-orange
    primary: green
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3LIZ_news

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/3liz

    - icon: fontawesome/brands/github
      link: https://github.com/3liz/

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/3liz

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCYYW2CTWR_84kB6pt2zCWbQ
